apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka-deployment
spec:
  selector:
    matchLabels:
      app: eureka-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: eureka-deployment
    spec:
      containers:
      - name: eureka-deployment
        image: nicolasgabrielli/eureka
        ports:
        - containerPort: 8761