apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileupload-deployment
  labels:
    app: fileupload-deployment
spec:
  selector:
    matchLabels:
      app: fileupload-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: fileupload-deployment
    spec:
      containers:
      - name: fileupload-deployment
        image: nicolasgabrielli/file-upload
        ports:
        - containerPort: 8083
        env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-service:8761/eureka/
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DATABASE
              value: fileuploaddb
---
apiVersion: v1
kind: Service
metadata:
  name: fileupload-service
  labels:
    app: fileupload-service
spec:
  selector:
    app: fileupload-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: NodePort