apiVersion: v1
kind: Service
metadata:
  name: fileupload-service
  labels:
    app: fileupload-service
spec:
  selector:
    app: fileupload-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer