apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-deployment
    spec:
      containers:
        - name: gateway-deployment
          image: nicolasgabrielli/gateway
          ports:
            - containerPort: 8090
          env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-service:8761/eureka/
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: spring.cloud.config.uri
              value: http://config-service:8081
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-deployment
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer