apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway-deployment
    spec:
      containers:
      - name: gateway-deployment
        image: nicolasgabrielli/gateway
        ports:
        - containerPort: 8090