apiVersion: v1
kind: Service
metadata:
  name: summary-service
  labels:
    app: summary-service
spec:
  selector:
    app: summary-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer