apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary-deployment
  labels:
    app: summary-deployment
spec:
  selector:
    matchLabels:
      app: summary-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: summary-deployment
    spec:
      containers:
      - name: summary-deployment
        image: nicolasgabrielli/summary
        ports:
        - containerPort: 8084