apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary-deployment
  labels:
    app: summary-deployment
spec:
  selector:
    matchLabels:
      app: summary-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: summary-deployment
    spec:
      containers:
        - name: summary-deployment
          image: nicolasgabrielli/summary
          ports:
            - containerPort: 8084
          env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-service:8761/eureka/
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: spring.cloud.config.uri
              value: http://config-service:8081
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DATABASE
              value: summarydb
---
apiVersion: v1
kind: Service
metadata:
  name: summary-service
  labels:
    app: summary-service
spec:
  selector:
    app: summary-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer