apiVersion: v1
kind: Service
metadata:
  name: supplier-service
  labels:
    app: supplier-service
spec:
  selector:
    app: supplier-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer