apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-deployment
  labels:
    app: supplier-deployment
spec:
  selector:
    matchLabels:
      app: supplier-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: supplier-deployment
    spec:
      containers:
      - name: supplier-deployment
        image: nicolasgabrielli/supplier
        ports:
        - containerPort: 8082